apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: default
spec:
  version: 8.15.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
